/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Main.SupplierReport;

import TheBusiness.Business.Business;
import TheBusiness.Supplier.SupplierDirectory;
import TheBusiness.Supplier.SupplierReport;
import TheBusiness.Supplier.SupplierSummary;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author natnichalerd
 */
public class SupplierReportJPanel extends javax.swing.JPanel {

    Business business;
    JPanel CardSequencePanel;
    
    
    /**
     * Creates new form SupplierReport
     */
    public SupplierReportJPanel(Business business, JPanel CardSequencePanel) {
        initComponents();
        
        this.business = business;
        this.CardSequencePanel = CardSequencePanel;
        
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblSupplierReport.getModel();
        model.setRowCount(0);
        
        SupplierReport supplierReport = business.getSupplierDirectory().generateSupplierReport();
        
        for (SupplierSummary supplierSummary : supplierReport.getSupplierSummaryList()) {
            Object[] row = new Object[5];
            row[0] = supplierSummary;
            row[1] = supplierSummary.getTotalSales();
            row[2] = supplierSummary.getLoyaltyScore();
            row[3] = supplierSummary.getAverageSpendingPerCustomer();
            row[4] = supplierSummary.getTop5SaleScore();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierReport = new javax.swing.JTable();

        jLabel1.setText("Supplier Report");

        tblSupplierReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Supplier Name", "Total Sales", "Loyalty Score", "Avg. Spending / Customer", "Top 5 Sale Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSupplierReport);
        if (tblSupplierReport.getColumnModel().getColumnCount() > 0) {
            tblSupplierReport.getColumnModel().getColumn(0).setResizable(false);
            tblSupplierReport.getColumnModel().getColumn(1).setResizable(false);
            tblSupplierReport.getColumnModel().getColumn(2).setResizable(false);
            tblSupplierReport.getColumnModel().getColumn(3).setResizable(false);
            tblSupplierReport.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplierReport;
    // End of variables declaration//GEN-END:variables

}